### PR TITLE
Feature/metobs data header parsing

### PR DESCRIPTION
**Pull request by mgcth**
**Description**

Parse metobs header into a dictionary. Still, store the raw header string.

### CODE REVIEW

**Comment by mgcth** [comment]
The `_parse_data` function should probably be split into two, one for the header and another for the data. But maybe leave it like this for now?

**Review by docNord — APPROVED** [review]
Really nice! You are probably right we should split it into two parsing jobs, but let's begin like this. We can create a new issue for improving code readability splitting them later.

**Comment by mgcth** [comment]
I fixed the split here.

**Comment by docNord** [comment]
Awesome!

**Pull request merged**
