### PR TITLE
Feature/0.2.0

### LINKED ISSUE #63: Strang time_from and time_to syntax differences
**Description**

The Strang `time_from` is a property and `time_to` is a callable. This was intentional, when `time_to`is called it generates the current time while `time_from` is static. It would be nice to unify their syntax but keep the functionality.

### LINKED ISSUE #66: Reduce method side effects
**Description**

Reduce or eliminate (as much as possible) side effects from our methods. Along these lines, remove the Metobs class altogether and just use the individual components.

### LINKED ISSUE #82: Mesan parameter listing
Currently, the output from calling Mesan parameters is appalingly difficult to read (a json dictionary style list which does not read well). There should be a function which writes the names of the parameters similar to the Metobs parameters function.

```
from smhi.mesan import Mesan
client =Mesan()
client.parameters

#Reads better, example:
import pandas as pd
df = pd.DataFrame(client.parameters)
df["name"]
```

### LINKED ISSUE #87: Lint of line
## Description

Investigate why `isinstanceof` can't be used here:

https://github.com/Ingenjorsarbete-For-Klimatet/ifk-smhi/blob/f988757507c4860d58b8cbc4d2ac8da0a75d35e5/tests/unit/test_unit_metobs.py#L397

### LINKED ISSUE #93: Simplify integration tests
## Description

Integration tests are a bit unwieldy now. Try and simplify them.

### LINKED ISSUE #96: Metfcts multipoint fails
## Description

Metfcts multipoint fails because SMHI's API does not respond on

`[...data.json?with-geo=false&downsample=2`

but this works

`...data.json`

Mesan which is based on exactly the same code (but different base URL) works. I guess it's something on SMHI's side.

### LINKED ISSUE #99: Consider using pydantic
## Description

We could use pydantic and return a data model/struct from the api calls. The bulk of data could still be in a pandas (or similar) object.

### LINKED ISSUE #101: Simplify tests
## Description

I don't think we have time to maintain the low-level tests we have now. Let's simplify them substantially by mainly testing input/output behaviour without (almost) any patching.

### LINKED ISSUE #105: Add pandera validation for dataframes
## Description

Add pandera validation of pandas dataframes.

### LINKED ISSUE #106: Naming
## Description

Rename data to something more meaningful, e.g. station or table.

@docNord could you think of something for the 4 APIs we are accessing?

### LINKED ISSUE #108: Add url to return types
## Description

Strang returns several fields, e.g. fetch URL. Add this to other APIs.

### PR DESCRIPTION
**Pull request by mgcth**
## Description

Work towards to 0.2.0 

- [x] Close #63
- [x] Close #66
- [x] Close #82
- [x] Close #87
- [x] Close #93
- [x] Close #96
- [x] Close #99
- [x] Close #101
- [x] Close #105
- [x] Close #106
- [x] Close #108

### CODE REVIEW

**Comment by docNord** [comment]
Are we returning pandas dfs across the board now?

**Comment by mgcth** [comment]
> Are we returning pandas dfs across the board now?

We are returning pydantic models, which usually contain a dataframe that is validated with pandera.

**Comment by mgcth** [comment]
@docNord, I'm not done with the tests, but I'd like to close this and simplify the tests in another PR.

**Review by docNord — APPROVED** [review]
Awesome work, I really appreciate the data structure and the setup, it is neat!

I might have appreciated a datetime format rather than string dates (```datetime.datetime.strptime(data.period["Tidsperiod (fr.o.m)"][0],"%Y-%m-%d %H:%M:%S"```), but we can leave that parsing for the parent class, if needed. 

Again, awesome!

**Comment by mgcth** [comment]
> I might have appreciated a datetime format rather than string dates (`datetime.datetime.strptime(data.period["Tidsperiod (fr.o.m)"][0],"%Y-%m-%d %H:%M:%S"`), but we can leave that parsing for the parent class, if needed.

Could you point to where in the code? If it is `validtime` from say `Mesan` where `get_multipoint` expects a string parameter, I don't think it's a good idea. Do you mean the index in the dataframes? Isn't that a date index already?

**Comment by docNord** [comment]
I mean in the ```data.period``` from and to fields :)

**Comment by mgcth** [comment]
Let's think about it, as Strang has those fields too.

**Pull request merged**
