### PR TITLE
version 0.1.0 -> 0.1.1

### LINKED ISSUE #53: Update version from 0.1.0
Using this code is not stable since despite all updates of the code, no progress of versions from the initial 0.1.0 has been made, causing issues with automatic version control etc.

### PR DESCRIPTION
**Pull request by docNord**
Need to start incrementing the version in order to allow for targeting specific installations, not to mess with people's usage of the code.

Closes #53.

### CODE REVIEW

**Review by mgcth — COMMENTED** [review]
Was thinking we should wait with this until we have a _release_ version. That is, we should follow the https://semver.org/ convention.

**Comment by docNord** [comment]
Nice reference! I was experiencing problems with an implementation where the latest functionality didn't load into the GitHub testing environment, but perhaps I can control that in the repo in question.

**Comment by mgcth** [comment]
In the meantime, you can probably do something like

```bash
pip install git+https://github.com/Ingenjorsarbete-For-Klimatet/ifk-smhi.git@811d566c7438bd5fe7480744135ce8a94991cb0a
```

where `811d566c7438bd5fe7480744135ce8a94991cb0a` is the currently latest commit in main.

**Comment by docNord** [comment]
Awesome, thanks!

**Comment by docNord** [comment]
Workaround suggested by @mgcth worked, closing PR.

**Pull request closed without merging**
