### PR TITLE
Feature/checks

### PR DESCRIPTION
**Pull request by mgcth**
Add bandit (to flake8) and mypy type checking.

### CODE REVIEW

**Review by docNord — APPROVED** [review]
Changes to URLs seem ok.

**Review by docNord — APPROVED** [review]

**Comment by docNord** [comment]
The checks don't work though, which is obviously a problem :)

**Comment by mgcth** [comment]
> The checks don't work though, which is obviously a problem :)

Yeah, idea was to fix them here too, hence the draft PR still :)

**Review by docNord — APPROVED** [review]

**Comment by mgcth** [comment]
I'll limit this PR to all checks but type checking. Will reopen a new PR for it later.

**Comment by mgcth** [comment]
We can merge this, there are some type errors left to fix, but lets do that in a separate PR.

**Comment by mgcth** [comment]
Fixed most type issues, skipping smhi for now as it'll change so much later.

Aso need to go over our unit tests as some of them miss parts of the code (i.e. I've added some extra checks in this PR).

**Comment by mgcth** [comment]
So, I stopped being lazy and just fixed the unit tests here. Ready to be merged.

**Review by docNord — DISMISSED** [review]

**Comment by mgcth** [comment]
@docNord, some conflicts, should be resolved now.

**Review by docNord — APPROVED** [review]

**Pull request merged**
