### PR TITLE
Feature/metobs nodes

### PR DESCRIPTION
**Pull request by mgcth**
**Description**

Implement Metobs API with standalone classes, and keep `Metobs` class. See issue #41.

**Checklist**

- [x] Add `Versions` node.
- [x] Make `Parameters`, `Stations`, `Periods` and `Data` nodes standalone.
- [x] Make `Parameters` possible to initialise without arguments.
- [x] Update `Metobs` to keep the same behaviour.
- [x] Update unit tests.
- [x] Update integration tests

**Examle**

Intended use

```Python
versions = Versions()  # defaults to json, can be omitted
parameters = Parameters()  # defaults to Version() and  version = "1.0", only supported
stations = Stations(parameters, 1)
periods = Periods(stations, 1)
data = Data(periods)  # defaults to "corrected-archive" in periods
```

Inspect objects with

```Python
versions.show
#  prints list of available versions

parameters.show
#  prints list of all parameters for that version

stations.show
#  prints list of all stations for that parameter

periods.show
#  prints list of all periods for that station

data.show
#  pandas DataFrame
```

We could exchange `show` with `print`, but I think `print` is strongly associated with a function, e.g. `print()`.

### CODE REVIEW

**Comment by mgcth** [comment]
This is getting ready for review.

One thing, we have these variables

- `variable`
- `parameter`
- `station`
- `period`

and we also have these variables which we might want to rename (tat is inside the classes)

- `variables` -> `variables_object`
- `parameters` -> `parameters_object`
- `stations` -> `stations_object`
- `periods` -> `periods_object`

The `_object` suffix is just a suggestion. Happy to hear if you have any other, @docNord!

**Comment by docNord** [comment]
Very good job! 

I think that the idea to change the var names to something more idiomatic would be good, yes - especially since we have the parameter, version etc variables. But perhaps they should reflect the ordered list style we talked about?

Something like:

parameters -> parameters_in_version
stations -> stations_with_parameter
periods -> periods_at_station

**Review by docNord — COMMENTED** [review]
The PR is good. I will approve it as soon as you settle on a logic for the "parameters - stations - periods" chain.

**Comment by mgcth** [comment]
Good suggestions, as those attributes are hidden from the user they can be on the long side.

**Review by docNord — DISMISSED** [review]

**Comment by mgcth** [comment]
@docNord, for tests to pass, we could have a `{{ date }}` key in the `head` string and do

`head = head.replace("{{ date }}", datetime.date.today().strftime("%Y-%m-%d"))`

**Comment by mgcth** [comment]
@docNord, see commit [9ac9a02](https://github.com/Ingenjorsarbete-For-Klimatet/ifk-smhi/pull/43/commits/9ac9a029e2568f70997ebad1784ecfd15ce43727). Is it too hacky?

**Comment by docNord** [comment]
It has to be the first of the current month in  order to pass though, not today's date. Also, we do not know that it will always be updated the first (some of the processes SMHI are working along are partially manual). Isn't it as good, and less cumbersome, to simply reduce the assert statement at the end to cover only the header up to [:-64] and thus not check the date part? We are still, I would argue, covering as much with the test but with a more robust and less cumbersome code...

**Comment by mgcth** [comment]
> It has to be the first of the current month in order to pass though, not today's date. Also, we do not know that it will always be updated the first (some of the processes SMHI are working along are partially manual). Isn't it as good, and less cumbersome, to simply reduce the assert statement at the end to cover only the header up to [:-64] and thus not check the date part? We are still, I would argue, covering as much with the test but with a more robust and less cumbersome code...

As the code is now, it's not today's date, but on the format `YYYY-MM-01`.

With that said, I'm fine with either approach. Update the code to your proposal if you think it's more robust.

**Review by docNord — APPROVED** [review]
Let's use this variant, then. After all, using all available information  in the test seems appropriate.

**Pull request merged**
