### PR TITLE
Feature/data format

### PR DESCRIPTION
**Pull request by mgcth**
**Description**

Unify the return formats of the different classes. Return simple lists instead of complex objects from parameters, valid time etc., and pandas DataFrame for _actual_ methods.

**Tasks**

- [x] Remove headers from get_data return
- [x] Return data in pandas DataFrame
- [x] Update tests
- [ ] ~Update docs~

### CODE REVIEW

**Comment by mgcth** [comment]
We should probably think about exactly what kind of data and structure of response we want to return here. Also, still need to cast Mesan, Metfcts and Strang data into Pandas. Maybe something you want to look into, @docNord?

**Comment by docNord** [comment]
Hi @mgcth ,

I started looking into the issue which this branch is based on, but then found this and deleted the little I had changed. Do you want to fill me in on the plan here and maybe I can get some work done tomorrow?

It looks as though your plan is to have all returns be of the form:
```pandas
data, header = ...
```
Is that correct?

**Comment by mgcth** [comment]
>     * [ ]  Remove headers from get_data return
> 
>     * [ ]  Return data in pandas DataFrame
> 
>     * [ ]  Update tests
> 
>     * [ ]  Update docs

See list above for what need to be done. I think we intended to remove the header return altogether and always return a pandas object.

**Comment by docNord** [comment]
Alright, I guess that works out. I don't get any data from `mesan` or `metfcts` when I try the default code in the documentation which is making it difficult to augment the code to return a dataframe, got a quick fix so that I can test my new code out?

**Comment by docNord** [comment]
I made the change for `Strang` @mgcth . Have a look and see what you think of it. Should be able to do the same stuff for `Metfcts` and `Mesan` too.

**Review by docNord — APPROVED** [review]
Since I made the changes, I think they are ok, yeah.

**Comment by mgcth** [comment]
@docNord, now only Mesan and Metfcts need updating to return data in basically the same format as Strang. After that, we can release an 0.1.0 version. Are you up to the task?

**Comment by docNord** [comment]
Updating Mesan? Sure, I will give it a go tomorrow. Probably reasonable to check dependencies before the release too, right? Perhaps SMHI needs some updating?

**Comment by mgcth** [comment]
Dependencies, as in packages we are using? Maybe create an issue about that?

I think only the parsing of the dicts is left. Should be possible to do a similar thing as in Strang, i.e. create two parsing methods for point and multipoint each. I can help out, but not tomorrow.

**Comment by docNord** [comment]
No I meant as in call structure for Metobs changed but maybe that's already dealt with?
Will get back tomorrow!

**Comment by mgcth** [comment]
I've just assumed SMHI has tests that's covering that :)

**Comment by docNord** [comment]
Started looking at this now.

Observations:
1. The data stored for Metobs tests is not working on my windows machine
2. The tests for the smhi-client are not covering correct output format from MetObs - the get_data function fails.

I will address 2. Then I will look into Mesan as per instructions. 1 will be ignored for now.

**Comment by docNord** [comment]
I am not getting the example from the documentation to run @mgcth :
```
>>> from smhi.mesan import Mesan
>>> client = Mesan()
>>> headers, data = client.get_point(16, 58)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: cannot unpack non-iterable NoneType object
>>>
```

What is wrong?

**Comment by mgcth** [comment]
There is only data output now, no header. Docs need updating.

All tests pass on my machine and GH, but if we have missing tests they should be added. What exact tests fail?

**Comment by docNord** [comment]
Ok will get back in a while, have some errands to run now.

**Comment by docNord** [comment]
When I read `get_point`, the data is returned in a nested fashion; Presumably, I get hourly results for one day from the data structure, which is organized such that:
```
data['timeSeries'][7]['parameters'][0]
```
Gives a dictionary which includes value and parameter name (for instance `t`, which presumably stands for 'temperature') and a bunch of metadata. Changing the first list ([7] above) changes the hour - length 24, and the second list ([0]) changes the parameter and has length 30.

While it is somewhat cumbersome, it is doable to parse into a dataframe with colums named by parameter. I am struggling a bit with the nestled call structure however, will need some time to parse this code to be able to add a "to_pandas" functionality :)

**Comment by docNord** [comment]
Multipoint returns in the same fasion, but only for one parameter (temperature) from what I gather. The list of `values` is a large list instead of the singular values returned by get_point.
```
>>> data_mp['timeSeries'][0]['parameters'][0].keys()
dict_keys(['name', 'levelType', 'level', 'unit', 'values'])
>>> data_mp['timeSeries'][0]['parameters'][0]['levelType']
'hl'
>>> data_mp['timeSeries'][0]['parameters'][0]['unit']      
'Cel'
>>> data_mp['timeSeries'][0]['parameters'][0]['name']
```

**Comment by mgcth** [comment]
Mesan is currently only a draft. `_format_multipoint` could format the data into a pandas DataFrame with a values and point column, with the point column holding shapley Points, for example.

I'm thinking valid and approved time can be lists/str, coordinates Shapley Polygon and Multipoint and parameter a list/dict or pandas. See if you like the get_point dataframe.

**Comment by docNord** [comment]
Made an attempt myself. See what you think @mgcth . I am going to teach my muay thai classes now, will be back around 20.30 for continued discussions :)

**Comment by mgcth** [comment]
Ok, looks like you want a pivoted table. In this way, `levelType` and `level` are dropped, or? Anyway, [63f8125](https://github.com/Ingenjorsarbete-For-Klimatet/ifk-smhi/pull/47/commits/63f81258ea64ccd805184660c9d06fa79cebd931) is a _cleaner_ way with only pandas methods.

**Comment by docNord** [comment]
Yes, I didn't understand what they were useful for and I figured it was easier to read a simple table, but I am of course open to any and all suggestions, it was just a thought. Nice cleanup of the code!

**Comment by mgcth** [comment]
See here for info about levels: https://opendata.smhi.se/apidocs/metanalys/parameters.html. Think we should include it. We should probably map the codes from that page too, bu lets do that in another PR.

**Comment by mgcth** [comment]
Now even this is getting messy, but [0fa0935](https://github.com/Ingenjorsarbete-For-Klimatet/ifk-smhi/pull/47/commits/0fa09357abd787a163a45be5b1efc2b819898233) includes the levels which are in [m] (not specified in the response, but on SMHI's API doc. The levels are just appended as columns at the end of the table.

**Comment by mgcth** [comment]
Mesan multipoint is parsed into a dataframe and tests are updated for everything. However, I'm unsure how to meaningfully run integration tests on Mesan's `get_point` and `get_multipoint` without mocking something out.

**Review by docNord — APPROVED** [review]

**Comment by mgcth** [comment]
Haha, but we aren't done here, or? I think some tests and updating docs are missing.

**Review by docNord — CHANGES_REQUESTED** [review]
Awesome work! 
The integration tests are not passing here at GitHub however. I saw you mentioned that in an earlier discussion point. Stuck?

**Comment by docNord** [comment]
Agreed, I jumped the gun a bit :)
Awesome work nonetheless!

**Comment by mgcth** [comment]
Want to fix the last tests update the docs?

**Comment by docNord** [comment]
I won't get anywhere tonight, but sure I can give it a shot this weekend!

**Comment by docNord** [comment]
I get 3 failing tests when I run on my old windowsmachine (the 2 integration tests for Mesan, but also 1 integration test for Metobs).

**Comment by docNord** [comment]
In terms of integration tests, would you consider it sufficient to check that:
[x] All data columns which should be there are
[x] The tail of the dataframe has a date close to today (either today or yesterday)
[x] Key variables are within a reasonable range
Because something like that, I think I could fix. Much more than that and I agree we will probably have to mock stuff out.

**Comment by docNord** [comment]
In order to solve S113 we need to change a substantial amount of code @mgcth - opinions?

**Comment by docNord** [comment]
What is it we should update in terms of the documentation? While somewhat short, the ´Mesan´ example looks alright to me?

**Comment by mgcth** [comment]
> What is it we should update in terms of the documentation? While somewhat short, the ´Mesan´ example looks alright to me?

Something about return type, format and how to work with it.

**Comment by mgcth** [comment]
> In order to solve S113 we need to change a substantial amount of code @mgcth - opinions?

S113?

**Comment by docNord** [comment]
> > In order to solve S113 we need to change a substantial amount of code @mgcth - opinions?
> 
> S113?

Lint error:
`12    S113 Requests call without timeout`

**Comment by mgcth** [comment]
It hasn't been an issue before. I wonder what in [63e6f1e](https://github.com/Ingenjorsarbete-For-Klimatet/ifk-smhi/pull/47/commits/63e6f1ed5d3294b4bc523dcf31fd21bc064c7b4a) triggered it.

Could we disable it globally in `.bandit`, raise an issue and implement it in 0.1.x?

**Comment by docNord** [comment]
I think that would be prudent, yes. I tried to quick fix it but got a bunch
of errors.

**Comment by mgcth** [comment]
Actually, let's open a new PR for that, so we can merge this.

**Review by docNord — APPROVED** [review]

**Pull request merged**
