### PR TITLE
fix data and _ mismatch line 169

### LINKED ISSUE #89: index error when using interpolate with get_data
I was playing around with the smhi client and tried to use interpolate. I got a dict cannot have index error and took a closer look at the code. It seems like there is a small bug with the order in which the get_data values are assigned. It can be found in line 169 in smhi.py and looks like this:
`_, tmpdata = self.get_data(parameter, nearby_station[0])`
I think you only need to switch places on the underscore and tmpdata and it will do as intended.

Thank you for providing this client!

Br,
Karl

### PR DESCRIPTION
**Pull request by docNord**
Closes #89

### CODE REVIEW

**Comment by mgcth** [comment]
How do you call 

https://github.com/Ingenjorsarbete-For-Klimatet/ifk-smhi/blob/403f521b920e9701babe3cd10085ae0b80ac298e/src/smhi/smhi.py#L131

to provoke the error reported in #89?

I can only manage to provoke another error from some non-thorough testing

```python
c.get_data(2, 6057, interpolate=0)
```

**Comment by docNord** [comment]
> How do you call
> 
> https://github.com/Ingenjorsarbete-For-Klimatet/ifk-smhi/blob/403f521b920e9701babe3cd10085ae0b80ac298e/src/smhi/smhi.py#L131
> 
> to provoke the error reported in #89?
> 
> I can only manage to provoke another error from some non-thorough testing
> 
> ```python
> c.get_data(2, 6057, interpolate=0)
> ```

Hmm, that is odd. I now get an error from MetObs when calling any station. MetObs is complaining that "Datum" is not included in the output from the SMHI API.
I will dowload a file manually and see if the format has changed somehow.

**Comment by docNord** [comment]
Update:
It seems there is a different return format specifically for parameter 2 @mgcth . I propose that you approve this PR and then we open a new issue to solve that problem. You should be able to recreate the issue reported with this code:
```
from smhi import smhi
s=smhi.SMHI()
data, _ = s.get_data(8,180960,interpolate=40)
```

**Comment by mgcth** [comment]
I'd like to reproduce the error here before I approve. How should I call `get_data` to reproduce the issue in #89 which you are fixing here?

**Comment by docNord** [comment]
Did you try the snippet in my previous comment @mgcth ?

**Comment by mgcth** [comment]
Sorry, missed it. Do we have tests for this function?

**Review by mgcth — APPROVED** [review]
I'll approve it now, looks correct. A refactor and tests would be nice.

**Pull request merged**
